theme: jekyll-theme-primer
title: Predicting Murder Rates in the U.S.
description: Keeping Italian Olives Pure!
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
