theme: jekyll-theme-primer
title: Homepage
description: Predicting Murder Rates in the U.S.
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
